### ISSUE TITLE
How is config.yaml built ?

### ISSUE THREAD

**Issue by pkutaj** [JupiterOne/docs#140]
Dear team, 

as per Erkang's comment on [ZD Forum](https://support.zendesk.com/hc/en-us/community/posts/360004378968/comments/360009246933) I am trying to fork your implementation but I can't find out how do you actually construct the `config.yaml` file. Could you please provide some input there ? Thank you! The `publish.js` script does work if I populate values in `config.yaml` manually (section/article IDs, etc.) but I am not sure how are you managing this file.

Pavol Kutaj
Support Engineer
Snowplow Analytics

**Comment by erkangz** [comment]
hey @pkutaj, you will need to manually "seed" the `config.yaml` file with some data. For example:

```
sections:
  - name: Getting started
    id: 360004204294
    articles:
      - title: 1/9 Configure Integrations
        file: ../guides/configure-integrations.md
```

This requires you to pre-create the section in ZD and has the section ID.  You only need the article `title` and `file` (relative path). The `publish.js` script will create a new article under that section, populate the ID and other information back to the `config.yaml` file, and it will use that to update existing articles. 

I hope this helps.
